import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const subject = sqliteTable(
  "subject",
  {
    id: integer("id").primaryKey(),
    object: text("object"),
    typeCode: integer("typeCode").notNull(),
    hiddenAt: integer("hiddenAt"),
    lessonPosition: integer("lessonPosition").notNull(),
    srsSystemId: integer("srsSystemId").notNull(),
    level: integer("level").notNull(),
    characters: text("characters"),
    slug: text("slug"),
    documentUrl: text("documentUrl"),
    meanings: text("meanings"),
    meaningMnemonic: text("meaningMnemonic"),
    meaningHint: text("meaningHint"),
    auxiliaryMeanings: text("auxiliaryMeanings"),
    readings: text("readings"),
    readingMnemonic: text("readingMnemonic"),
    readingHint: text("readingHint"),
    componentSubjectIds: text("componentSubjectIds"),
    amalgamationSubjectIds: text("amalgamationSubjectIds"),
    visuallySimilarSubjectIds: text("visuallySimilarSubjectIds"),
    partsOfSpeech: text("partsOfSpeech"),
    contextSentences: text("contextSentences"),
    pronunciationAudios: text("pronunciationAudios"),
    audioDownloadStatus: integer("audioDownloadStatus").notNull(),
    searchTarget: text("searchTarget"),
    smallSearchTarget: text("smallSearchTarget"),
    assignmentId: integer("assignmentId").notNull(),
    availableAt: integer("availableAt"),
    burnedAt: integer("burnedAt"),
    passedAt: integer("passedAt"),
    resurrectedAt: integer("resurrectedAt"),
    startedAt: integer("startedAt"),
    unlockedAt: integer("unlockedAt"),
    passed: integer("passed").notNull(),
    resurrected: integer("resurrected").notNull(),
    srsStage: integer("srsStage").notNull(),
    levelProgressScore: integer("levelProgressScore").notNull(),
    lastIncorrectAnswer: integer("lastIncorrectAnswer"),
    assignmentPatched: integer("assignmentPatched").notNull(),
    studyMaterialId: integer("studyMaterialId").notNull(),
    meaningNote: text("meaningNote"),
    meaningSynonyms: text("meaningSynonyms"),
    readingNote: text("readingNote"),
    studyMaterialPatched: integer("studyMaterialPatched").notNull(),
    reviewStatisticId: integer("reviewStatisticId").notNull(),
    meaningCorrect: integer("meaningCorrect").notNull(),
    meaningIncorrect: integer("meaningIncorrect").notNull(),
    meaningMaxStreak: integer("meaningMaxStreak").notNull(),
    meaningCurrentStreak: integer("meaningCurrentStreak").notNull(),
    readingCorrect: integer("readingCorrect").notNull(),
    readingIncorrect: integer("readingIncorrect").notNull(),
    readingMaxStreak: integer("readingMaxStreak").notNull(),
    readingCurrentStreak: integer("readingCurrentStreak").notNull(),
    percentageCorrect: integer("percentageCorrect").notNull(),
    leechScore: integer("leechScore").notNull(),
    statisticPatched: integer("statisticPatched").notNull(),
    frequency: integer("frequency").notNull(),
    joyoGrade: integer("joyoGrade").notNull(),
    jlptLevel: integer("jlptLevel").notNull(),
    pitchInfo: text("pitchInfo"),
    strokeData: text("strokeData"),
    characterImages: text("characterImages"),
    dataUpdatedAt: integer("dataUpdatedAt"),
  },
  (table) => [
    index("index_subject_level").on(table.level),
    index("index_subject_characters").on(table.characters),
    index("index_subject_availableAt").on(table.availableAt),
    index("index_subject_burnedAt").on(table.burnedAt),
    index("index_subject_startedAt").on(table.startedAt),
    index("index_subject_unlockedAt").on(table.unlockedAt),
    index("index_subject_srsStage").on(table.srsStage),
    index("index_subject_dataUpdatedAt").on(table.dataUpdatedAt),
  ],
);

export const srsSystem = sqliteTable("srs_system", {
  id: integer("id").primaryKey(),
  name: text("name"),
  description: text("description"),
  stages: text("stages"),
  unlockingStagePosition: integer("unlockingStagePosition").notNull(),
  startingStagePosition: integer("startingStagePosition").notNull(),
  passingStagePosition: integer("passingStagePosition").notNull(),
  burningStagePosition: integer("burningStagePosition").notNull(),
});

export const levelProgression = sqliteTable("level_progression", {
  id: integer("id").primaryKey(),
  abandonedAt: integer("abandonedAt"),
  completedAt: integer("completedAt"),
  createdAt: integer("createdAt"),
  passedAt: integer("passedAt"),
  startedAt: integer("startedAt"),
  unlockedAt: integer("unlockedAt"),
  level: integer("level").notNull(),
  dataUpdatedAt: integer("dataUpdatedAt"),
});

export const properties = sqliteTable("properties", {
  name: text("name").primaryKey(),
  value: text("value").notNull(),
});
